export const GET_ITEMS = "GET_ITEMS";
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";
export const GET_ITEM_FAIL = "GET_ITEM_FAIL";

export const POST_ITEMS = "POST_ITEMS";
export const POST_ITEM_SUCCESS = "POST_ITEM_SUCCESS";
export const POST_ITEM_FAIL = "POST_ITEM_FAIL";

export const GET_HISTORY_ITEMS = "GET_ITEMS";
export const GET_HISTORY_ITEM_SUCCESS = "GET_HISTORY_ITEM_SUCCESS";
export const GET_HISTORY_ITEM_FAIL = "GET_HISTORY_ITEM_FAIL";
