export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";

export const GET_SELECTED_CONTACT = "GET_SELECTED_CONTACT";
export const GET_SELECTED_CONTACT_SUCCESS = "GET_SELECTED_CONTACT_SUCCESS";
export const GET_SELECTED_CONTACT_FAIL = "GET_SELECTED_CONTACT_FAIL";

// export const POST_ITEMS = "POST_ITEMS";
// export const POST_ITEM_SUCCESS = "POST_ITEM_SUCCESS";
// export const POST_ITEM_FAIL = "POST_ITEM_FAIL";

// export const GET_HISTORY_ITEMS = "GET_ITEMS";
// export const GET_HISTORY_ITEM_SUCCESS = "GET_HISTORY_ITEM_SUCCESS";
// export const GET_HISTORY_ITEM_FAIL = "GET_HISTORY_ITEM_FAIL";
