export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";

export const GET_SELECTED_CONTACT = "GET_SELECTED_CONTACT";
export const GET_SELECTED_CONTACT_SUCCESS = "GET_SELECTED_CONTACT_SUCCESS";
export const GET_SELECTED_CONTACT_FAIL = "GET_SELECTED_CONTACT_FAIL";

export const POST_MESSAGE = "POST_MESSAGE";
export const POST_MESSAGE_SUCCESS = "POST_MESSAGE_SUCCESS";
export const POST_MESSAGE_FAIL = "POST_MESSAGE_FAIL";

export const GET_MESSAGES = "GET_MESSAGES";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";

export const GET_CONTACT_HISTORY = "GET_CONTACT_HISTORY";
export const GET_CONTACT_HISTORY_SUCCESS = "GET_CONTACT_HISTORY_SUCCESS";
export const GET_CONTACT_HISTORY_FAIL = "GET_CONTACT_HISTORY_FAIL";
